USE EduTec
GO
SELECT IDALUMNO,IDCURSOPROG,PROMEDIO 
FROM MATRICULA 
WHERE  IDCURSOPROG = 2 	
ORDER BY PROMEDIO DESC
GO
SELECT TOP 3 
IDALUMNO,IDCURSOPROG,PROMEDIO 
FROM MATRICULA 
WHERE  IDCURSOPROG=2 	
ORDER BY PROMEDIO DESC
GO
SELECT  TOP 3 WITH TIES --Considera los empates
IDALUMNO,IDCURSOPROG,PROMEDIO 
FROM MATRICULA 
WHERE  IDCURSOPROG=2 	
ORDER BY PROMEDIO DESC
GO
-- GENERACION DE RESUMENES DE DATOS

USE EDUTEC
GO
SELECT COUNT(*) AS [Numero de Alumnos] 
FROM ALUMNO
GO
--contar registros COUNT no considera nulos
SELECT COUNT(DirAlumno) AS [Numero de Alumnos] 
FROM ALUMNO
GO
SELECT COUNT(IDALUMNO) AS [Numero de MATRICULADOS] 
FROM MATRICULA
GO
SELECT COUNT(FecMatricula) AS [Numero de MATRICULADOS] 
FROM MATRICULA
GO

SELECT MAX(PRETARIFA) AS COSTO_MAYOR
FROM TARIFA
GO
SELECT * FROM TARIFA
GO
SELECT MIN(PRETARIFA) AS COSTO_MENOR 
FROM TARIFA
GO
SELECT AVG(PRETARIFA) AS COSTO_PROMEDIO
FROM TARIFA
GO
--
USE NORTHWIND
GO
SELECT MAX(UNITPRICE) FROM PRODUCTS
GO
SELECT 
	PRODUCTNAME, 
	MAX(UNITPRICE) AS COSTO_MAYOR 
FROM PRODUCTS
GO

--SUBCONSULTAS
SELECT 
	ProductName, 
	UnitPrice 
FROM PRODUCTS
WHERE 
UnitPrice = (SELECT MAX(UNITPRICE) FROM PRODUCTS)
GO